function radpt_south(start, stop, filename, doabs)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
%  function radpt(start, stop, filename)
%
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% wrapper around radio pointing schedule that doesn't read in unecessary
% registers.

  regs={'array.frame.received'...
	'array.frame.utc double',...
	'array.frame.features',...
	'array.weather.utc double',...
	'array.weather.pressure double',...
	'array.weather.airTemperature double',...
	'array.weather.windSpeed[0] double',...
	'array.weather.windDirection[0] double',...
	'array.weather.status double',...
	'array.weather.relativeHumidity double',...
	'antenna0.thermal.ccHeaterCurrent double',...
	'antenna0.thermal.lsTemperatureSensors double',...
	'antenna0.thermal.ccTemperatureLoad double',...
	'antenna0.thermal.ccColdPlate double', ...
	'antenna0.thermal.utc double',...
	'antenna0.thermal.dlpTemperatureSensors double',...
	'antenna0.tracker.lst double',...
	'antenna0.tracker.lacking double',...
	'antenna0.tracker.equat_geoc double',...
	'antenna0.tracker.horiz_topo double',...
	'antenna0.tracker.horiz_mount double',...
	'antenna0.tracker.flexure double',...
	'antenna0.tracker.horiz_off double',...
	'antenna0.tracker.tilts double',...
	'antenna0.tracker.fixedCollimation double',...
	'antenna0.tracker.encoder_off double',...
	'antenna0.tracker.sky_xy_off double',...
	'antenna0.tracker.source string',...
	'antenna0.tracker.scan_off double',...
	'antenna0.tracker.refraction double',...
	'antenna0.tracker.ut1utc double',...
	'antenna0.tracker.eqneqx double',...
	'antenna0.tracker.utc double',...
	'antenna0.tracker.time_diff double',...
	'antenna0.tracker.offSource double',...
	'antenna0.tracker.siteActual double',...
	'antenna0.tracker.siteFiducial double',...
	'antenna0.servo.utc double',...
	'antenna0.servo.fast_az_pos double',...
	'antenna0.servo.fast_el_pos double',...
	'antenna0.servo.fast_az_err double',...
	'antenna0.servo.fast_el_err double',...
	'antenna0.servo.actual_current_az1[0] double',...
	'antenna0.servo.actual_current_az2[0] double',...
	'antenna0.servo.actual_current_el1[0] double',...
	'antenna0.frame.utc double',...
	'antenna0.frame.received double',...
	'antenna0.receiver.flags double',...
	'antenna0.receiver.utc double',...
	'antenna0.receiver.data double',...
	'antenna0.receiver.diagnostics double',...
	'antenna0.receiver.drainCurrent double',...
	'antenna0.receiver.drainVoltage double',...
	'antenna0.receiver.gateVoltage double',...
};

if(nargin<4)
  doabs = 0;
end


d = read_arcSouth(start, stop);
d=south_to_north(d);

%d = pipe_read([],[],d);

% remove the load 
plotparams.save = 0;
plotparams.plot = 1;
plotparams.interactive = 1;
parm = [];
field = '';

% cold load needs alpha wrapper
% make sure the alpha database is uptodate
%isup2date = checkAlphaDatabase((d.array.frame.utc(1)));
%if(~isup2date)
%  display('Your alpha database is not up to date');
%  display('You will update the database');
%  display('Don''t fudge it up');
%  updateAlphaDatabase(last(d.array.frame.utc));
%end
% JL removed
%d = alphaWrapper(d, plotparams, parm, field);

% JL removed.
% remove the cold load
%d = loadWrapper(d, plotparams, parm, field);

% flag for RFI
% fucking RFI flagging is awful and flagging EVERYTHING in pointing
% scheds
%parm.rfi.short = [inf inf inf inf];
%parm.rfi.long =  [ inf inf inf inf inf];
%parm.rfi.smooth = [inf];
%parm.rfi.rejection = [inf];


%d = rfiWrapper(d, plotparams, parm, field);

switch(doabs)
  case 1
    d.antenna0.receiver.data(:,[1 8]) = d.antenna0.receiver.data(:,[1 8])+200;
  
  case 2
    d.antenna0.receiver.data(:,[1 8]) = 300 - d.antenna0.receiver.data(:,[1 ...
	  8]);
end




radioPointing(d, 'scan', filename);

return;
